os:
  - osx

language: cpp

sudo: required
dist: trusty
osx_image: xcode7

cache:
  directories:
  - $HOME/.macports-ci-ccache

before_install:
# this is required for curl to work correctly:
  - export COLUMNS=80
  - if test -z "$PRE" ; then PRE=/opt/local ; fi
  - sudo chmod +x macports-ci 
  - sudo ./macports-ci install --prefix="$PRE" $OPT
  - PATH="$PRE/bin:$PATH"
  - if test "$PRE" = /opt/local ; then ./macports-ci ccache ; fi
  - which port
  - pwd
   - brew uninstall boost
   - brew install boost@1.57
   - brew link boost@1.57 --force
  - sudo port -N install boost db48 openssl miniupnpc qrencode qt4-mac
  - ls /usr/local/
  - ls /opt/local/include/
  - ls /opt/local/include/boost
  - ls /opt/local/include/db48
  - ls /opt/local/lib/
  - ls /opt/local/lib/db48
  - cd /usr/local/include 
  - sudo ln -s ../opt/openssl/include/openssl .
  - cd /Users/travis/build/getdatcrypto/katana
  - chmod 755 src/leveldb/build_detect_platform
  - chmod 755 *
  - cd ../..
  
script: 
  - cd src
  - make -f makefile.osx RELEASE=true
